name: Docker Image CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Deploy to server via SSH
        uses: appleboy/ssh-action@v0.1.9
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/linka/linka-frontend
            
            # Pull the latest changes from the repository
            git pull
            
            # Navigate to the project directory
            cd ..
            
            # Stop and remove existing containers (also removes networks)
            docker-compose down --remove-orphans
            
            # Prune unused networks and volumes (optional)
            docker network prune -f
            docker volume prune -f
            
            # Start containers with the updated image
            docker-compose up -d --build
